### ISSUE TITLE
Destructive usage of strtok()

### ISSUE THREAD

**Issue by Skorob0g** [javach/dc_lab_1#1]
strtok() usage is destructive for sourcce string. You should copy the string in parser functions first to safely use it.

**Comment by javach** [comment]
In the only case it matters it has been acknowledged and the string is copied before parsing.

**Comment by Skorob0g** [comment]
It makes code non-extensible.
If you want to use multiply strtok's you must create a copy for each of them in the command function.
Copying it inside parser function is far more clean.

**Comment by javach** [comment]
Ok, you're right. Please, open PR with comments on functions where strtok() is used.
